// EXTRA TESTCASES ADDED HERE SINCE interpolate.spec.js has  // DO NOT EDIT THIS FILE comment in it 

const { interpolate } = require('./interpolate')

describe('interpolate', () => {
    it('should ignore an open delimiter without a closing delimiter for multiple times', () => {
        const result = interpolate('Hi {firstname and {lastname, how are you today?', { firstname: 'John', lastname: 'Doe' }, { leftDelimiter: '{', rightDelimiter: '}' })
        const expected = 'Hi {firstname and {lastname, how are you today?'
        expect(result).toEqual(expected)
    })
    it('should interpolate a multiple variables with differet delimter', () => {
        const result = interpolate('Hi {firstname} {lastname}, how are you today?', { firstname: 'John', lastname: 'Doe' }, { leftDelimiter: '{', rightDelimiter: '}' });
        const expected = 'Hi John Doe, how are you today?';
        expect(result).toEqual(expected)
    });
    it('should interpolate a multiple variables with not all session object exists', () => {
        const result = interpolate('Hi {firstname} {lastname}, how are you today?', { firstname: 'John' }, { leftDelimiter: '{', rightDelimiter: '}' });
        const expected = 'Hi John , how are you today?';
        expect(result).toEqual(expected)
    });
});
